### ISSUE TITLE
Create Template for Icons for Telegram Chats

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/meta-dao-ops#35]
I'd like us to be consistent with branding in all that we do, so this serves two fold:
1. It makes it easier to see within telegram
2. It makes it feel like we're partners, we're building already for / with them.

We've got something currently, but that's not fitting well and looks kind of sloppy, I'm not sure the best way to do this right now, but we should come up with something such that we have something that looks good and is easy for us to create quickly.

**Comment by nicovrg** [comment]
i've asked @tmskrtsz to help me and we found something that i believe strike a good balance between thumbnail visibility & professionalism. since we don't have figma pro, i took his template over to another figma (the other metadao that marie made for vota) so i can now do these thumnail myself directly without bothering anyone.

only issue is that i can't change telegram groupchat thumbnail where i'm not the group owner so i'll have to ask chat owner to do it

**Comment by R-K-H** [comment]
Fine, just get them generated and I'll be sure to push it through if I can.
