### ISSUE TITLE
Create System for Organizing Telegram Chats

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/meta-dao-ops#36]
Currently I paid for and use folders, I'd recommend the same of anyone doing outreach, but we need to document this as part of our process so that we can afford no excuses for missing things or not continuing conversations.

**Comment by nicovrg** [comment]
telegram folders aren't part of paid telegram, we can use them too! and we do :)

one thing that would be great though is to add us to the channels and to notify us when you add us. numerous chats i found out days later or i found out after talking to other futards that the room existed because i wasn't notified so didn't scroll through unread tg msgs & add the room to my metadao folder

also the room creator should share link so we can add it to the notion project page

**Comment by nicovrg** [comment]
i think this should be closed now
